AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for AutoGluon-Cloud to run on SageMaker'

Resources:
  AGCloudSageMakerBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub
        - '${AWS::StackName}-bucket-${suffix}'
        - suffix: !Select [0, !Split ['-', !Select [2, !Split ['/', !Ref 'AWS::StackId']]]]
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  AGCloudSageMakerExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub '${AWS::StackName}-execution-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service: sagemaker.amazonaws.com
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: !Sub '${AWS::StackName}-custom-policy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: SageMaker
                Effect: Allow
                Action:
                  - sagemaker:CreateTrainingJob
                  - sagemaker:CreateModel
                  - sagemaker:CreateEndpoint
                  - sagemaker:CreateEndpointConfig
                  - sagemaker:CreateTransformJob
                  - sagemaker:DescribeTrainingJob
                  - sagemaker:DescribeTransformJob
                  - sagemaker:DescribeEndpoint
                  - sagemaker:DescribeEndpointConfig
                  - sagemaker:DescribeModel
                  - sagemaker:DeleteEndpoint
                  - sagemaker:DeleteEndpointConfig
                  - sagemaker:DeleteModel
                  - sagemaker:InvokeEndpoint
                  - sagemaker:AddTags
                  - sagemaker:ListTags
                  - sagemaker:ListEndpoints
                  - sagemaker:ListEndpointConfigs
                  - sagemaker:ListModels
                  - sagemaker:ListTrainingJobs
                  - sagemaker:ListTransformJobs
                  - s3:ListAllMyBuckets
                Resource: '*'

              - Sid: PassExecutionRole
                Effect: Allow
                Action: iam:PassRole
                Resource: !Sub 'arn:aws:iam::${AWS::AccountId}:role/${AWS::StackName}-execution-role'
                Condition:
                  StringEquals:
                    iam:PassedToService: sagemaker.amazonaws.com

              - Sid: S3Bucket
                Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:GetBucketLocation
                  - s3:CreateBucket
                Resource:
                  - !Sub 'arn:aws:s3:::${AGCloudSageMakerBucket}'
                  - 'arn:aws:s3:::sagemaker-*'

              - Sid: S3Object
                Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:GetObjectAcl
                  - s3:PutObjectAcl
                  - s3:AbortMultipartUpload
                Resource:
                  - !Sub 'arn:aws:s3:::${AGCloudSageMakerBucket}/*'
                  - 'arn:aws:s3:::sagemaker-*/*'

              - Sid: ECRPull
                Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:BatchGetImage
                  - ecr:GetDownloadUrlForLayer
                  - ecr:DescribeRepositories
                  - ecr:DescribeImages
                Resource: '*'

              - Sid: CloudWatchLogs
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogStreams
                  - logs:GetLogEvents
                Resource: !Sub 'arn:aws:logs:*:${AWS::AccountId}:log-group:/aws/sagemaker/*'

Outputs:
  BucketName:
    Description: S3 bucket where AutoGluon-Cloud will save trained predictors
    Value: !Ref AGCloudSageMakerBucket

  RoleARN:
    Description: ARN of the created IAM role for AutoGluon-Cloud to run on SageMaker
    Value: !GetAtt AGCloudSageMakerExecutionRole.Arn
