SAGEMAKER = "sagemaker"
TABULAR_SAGEMAKER = "tabular_sagemaker"
MULTIMODL_SAGEMAKER = "multimodal_sagemaker"
TIMESERIES_SAGEMAKER = "timeseries_sagemaker"
RAY = "ray"
RAY_AWS = "ray_aws"
TABULAR_RAY_AWS = "tabular_ray_aws"
