name: "Test Cloud Module"
inputs:
  submodule-to-test:
    required: true
  ag_version:
    required: false
    default: source

runs:
  using: "composite"
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::369469875935:role/AutoGluonCloudCIRole
        role-duration-seconds: 7200
        aws-region: us-east-1
    - name: Test Cloud Submodule
      shell: bash
      run: |
        chmod +x ./.github/workflow_scripts/test_cloud.sh && ./.github/workflow_scripts/test_cloud.sh '${{ inputs.submodule-to-test }}' '${{ inputs.ag_version }}'
