import base64
import copy
import logging
import os
import shutil
import stat
import tarfile
import zipfile
from datetime import datetime, timezone

import PIL
from PIL import Image

logger = logging.getLogger(__name__)


def read_image_bytes_and_encode(image_path):
    image_obj = open(image_path, "rb")
    image_bytes = image_obj.read()
    image_obj.close()
    b85_image = base64.b85encode(image_bytes).decode("utf-8")

    return b85_image


def convert_image_path_to_encoded_bytes_in_dataframe(dataframe, image_column):
    assert image_column in dataframe, "Please specify a valid image column name"
    dataframe = copy.deepcopy(dataframe)
    dataframe[image_column] = [read_image_bytes_and_encode(path) for path in dataframe[image_column]]

    return dataframe


def zipfolder(output_filename, dir_name):
    """
    Zip a folder while preserving the directory structure

    Example
        If dir_name is temp, and the structure is as follow:
        home
        |--- temp
             |---train
             |---test
        The zipped file will also has temp as the base directory instead of train and test
    """
    dir_name = os.path.abspath(dir_name)
    root_dir = os.path.dirname(dir_name)
    base_dir = os.path.basename(dir_name)
    shutil.make_archive(output_filename, "zip", root_dir, base_dir)


def is_compressed_file(filename):
    return tarfile.is_tarfile(filename) or zipfile.is_zipfile(filename)


def is_image_file(filename):
    try:
        Image.open(filename)
    except PIL.UnidentifiedImageError:
        # Not an image
        return False
    return True


# Copied verbatim from autogluon.common.loaders.load_archive.
def safe_unpack_archive(path: str | os.PathLike, dest_dir: str | os.PathLike) -> None:
    """Safely extract a zip or tar archive, rejecting path traversal and unsafe entries.

    The archive format is auto-detected; supports zip and tar (incl. gz/bz2/xz).
    """
    path = str(path)
    dest_dir = os.path.realpath(str(dest_dir))

    if zipfile.is_zipfile(path):
        with zipfile.ZipFile(path, "r") as zf:
            _validate_zip(zf, dest_dir)
            zf.extractall(dest_dir)  # nosec B202
    elif tarfile.is_tarfile(path):
        with tarfile.open(path) as tf:
            _validate_tar(tf, dest_dir)
            tf.extractall(dest_dir)  # nosec B202
    else:
        raise ValueError(f"Unsupported or unrecognized archive format: {path}")


def _validate_zip(zf: zipfile.ZipFile, dest_dir: str) -> None:
    for member in zf.infolist():
        member_path = os.path.realpath(os.path.join(dest_dir, member.filename))
        if not member_path.startswith(dest_dir + os.sep) and member_path != dest_dir:
            raise ValueError(f"Path traversal detected: {member.filename} would extract outside {dest_dir}")
        if stat.S_ISLNK(member.external_attr >> 16):
            raise ValueError(f"Archive contains symlink: {member.filename}")


def _validate_tar(tf: tarfile.TarFile, dest_dir: str) -> None:
    for member in tf.getmembers():
        member_path = os.path.realpath(os.path.join(dest_dir, member.name))
        if not member_path.startswith(dest_dir + os.sep) and member_path != dest_dir:
            raise ValueError(f"Path traversal detected: {member.name} would extract outside {dest_dir}")
        if member.issym() or member.islnk():
            raise ValueError(f"Archive contains link: {member.name}")
        if member.isdev() or member.isfifo():
            raise ValueError(f"Archive contains special file: {member.name}")


def split_pred_and_pred_proba(prediction):
    """
    Split concatenated prediction generated by the serving script.
    Also remove the appended `proba` suffix by the serving script.

    Parameters
    ----------
    prediction: pd.DataFrame
        DataFrame consisting predicition and predict_proba (if available), i.e.
                     class   <=50K_proba   >50K_proba
        0      <=50K_proba      0.949797     0.050203
        1      <=50K_proba      0.945973     0.054027
    """
    pred = prediction.iloc[:, 0]
    pred_proba = None
    if len(prediction.columns) > 1:
        pred_proba = prediction.iloc[:, 1:]
        pred_proba.columns = [c.removesuffix("_proba") for c in pred_proba.columns]

    return pred, pred_proba


def get_utc_timestamp_now():
    return datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S")
